---
layout: cv
title: Logan Lay's CV
---
# Logan Lay

<div id="webaddress">
<a href="lay23004@byui.edu">lay23004@byui.edu</a>
| <a href="https://github.com/Logan-Lay21">Github</a>
</div>


## Summary
Hardworking computer science student seeking to apply skills learned through education in a professional, relevant setting. Customer service strengthened attention to detail, reliability, and positivity under pressure. Committed to continuous improvement and problem solving. Quick learner with experience as a camp counselor and math tutor, providing strong communication skills with clients and colleagues. Loves serving others and finds joy in helping people understand simple and complex concepts.

## Education
**BS in Computer Science** | Aug 2023 - Dec 2026

Brigham Young University-Idaho - Rexburg, Idaho



**General Education** | Aug 2020 - Dec 2020

Sierra College - Rocklin, California

## Experience

**Teachers Assistant** | Jan 2025 - Present

BYU-Idaho - Rexburg, ID

* Guide students 10+ hours a week in understanding common and complex math problems through examples and verbal communication
* Receive weekly training instruction to construct good teaching habits

**Math Tutor** | Jan 2024 - Present

BYU-Idaho Math Center - Rexburg, ID

* Guide students 10 hours a week in understanding common and complex math problems through examples and verbal communication; attend weekly training meetings to construct good teaching habits
* Addressed students questions through 5+ online chats at a time and discussed answers to problems and explained solutions
* Tutor all classes of Calculus I and below

**Manager/Owner** | 2012-2021

Lay's Landscaping - Rocklin, CA

* Developed a solid client base of weekly mow, edge, blow clients. Marketed on Next Door and Facebook groups to find business
* Contacted potential clients to provide an estimate for work, set up long-term contracts, invoice, money collect, and perform the work. Additionally enjoyed guiding clients on what types of plants are good for certain locations in the yard

## Skills

* Cooperative team member
* Extremely organized
* Quick learner, ready to face a challenge
* Outstanding interpersonal skills
* Attention to detail
* Energetic
* Strong verbal communication
* English (Native)
* Python experience
* C# experience
* Basic SQL experience
* HTML, CSS, and Javascript experience

## Activities and Honors

* Eagle Scout Rank with the Boy Scouts of America, March 2018
* Full-time volunteer for The Church of Jesus Christ of Latter-Day Saints in St. Louis Missouri (August 2021-August 2023)
* Graduated high school a year early with honors (Summer 2020)
* Managed and ran a landscaping business, starting it from scratch
* Competed in 2025 USU hackathon 



<!-- ### Footer

Last updated: May 2013 -->